# -*- mode: ruby -*-
# vi: set ft=ruby :

# Vagrantfile API/syntax version. Don't touch unless you know what you're doing!
VAGRANTFILE_API_VERSION = "2"

Vagrant.configure(VAGRANTFILE_API_VERSION) do |config|

 # if Vagrant.has_plugin?("vagrant-proxyconf")
	# see https://docs.docker.com/articles/systemd/#http-proxy for proxy settings
    #config.proxy.http     = "http://proxy-fr-croissy.gemalto.com:8080"
    #config.proxy.https    = "http://proxy-fr-croissy.gemalto.com:8080"
#	config.proxy.no_proxy = "localhost,127.0.0.1,/var/run/docker.sock"
# end
  
  # Every Vagrant virtual environment requires a box to build off of.
  config.vm.box = "ubuntu/xenial64"
  #config.vm.provision :shell, :path => "bootstrap.sh"
  # vagrant plugin install vagrant-vbguest
  config.vbguest.auto_update = true

  config.vm.network "forwarded_port", guest: 80, host: 9080
  config.vm.network "forwarded_port", guest: 3306, host: 3308
  config.vm.network "forwarded_port", guest: 1080, host: 1080
  config.vm.network "forwarded_port", guest: 1025, host: 1025
  config.vm.network "forwarded_port", guest: 8085, host: 8085
  config.vm.synced_folder ".", "/vagrant/"
  config.vm.provider "virtualbox" do |v|
    v.memory = 2048
    v.cpus = 1
    v.name = "mbbvm"
  end
end
